# Generated by Django 4.2.1 on 2023-05-23 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Наименование модели')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модель оборудования',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['id'], 'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Продукцию', 'verbose_name_plural': 'Тип продукции'},
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='model',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sma.equipment', verbose_name='Тип оборудования'),
        ),
    ]
