# Generated by Django 4.2.1 on 2023-05-23 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Наименование статьи затрат')),
            ],
            options={
                'verbose_name': 'Статью затрат',
                'verbose_name_plural': 'Статьи затрат',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Наименование единицы измерения')),
            ],
            options={
                'verbose_name': 'Единицу измерения',
                'verbose_name_plural': 'Единицы измерения',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id'], 'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Наименование показателя')),
                ('count', models.CharField(max_length=70, verbose_name='Значение')),
                ('measure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sma.measure', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
                'ordering': ['id'],
            },
        ),
    ]
