# Generated by Django 4.2.1 on 2023-05-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0006_costitem_measure_alter_service_options_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='price',
            field=models.CharField(default='5', max_length=70, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
