# Generated by Django 4.2.1 on 2023-05-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0007_model_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discount',
            field=models.CharField(blank=True, max_length=70, verbose_name='Скидка, %'),
        ),
    ]
