# Generated by Django 4.2.1 on 2023-05-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0008_service_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='price',
        ),
    ]
