# Generated by Django 4.2.1 on 2023-05-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0009_remove_model_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='discount',
        ),
        migrations.AddField(
            model_name='model',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
