# Generated by Django 4.2.1 on 2023-05-23 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0010_remove_service_discount_model_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discount',
            field=models.IntegerField(blank=True, help_text='В процентах', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Размер скидки'),
        ),
    ]
