# Generated by Django 4.2.1 on 2023-05-23 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0011_service_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Количество, шт.'),
        ),
    ]
