# Generated by Django 4.2.1 on 2023-05-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0013_remove_indicator_count_indicator_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Значение'),
        ),
    ]
