# Generated by Django 4.2.1 on 2023-05-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0016_indicator_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Наименование показателя')),
                ('value', models.DurationField(blank=True, null=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
                'ordering': ['id'],
            },
        ),
    ]
