# Generated by Django 4.2.1 on 2023-05-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0017_testr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testr',
        ),
    ]
