# Generated by Django 4.2.1 on 2023-05-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0018_delete_testr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Наименование оборудования'),
        ),
    ]
