# Generated by Django 4.2.1 on 2023-05-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0019_alter_equipment_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostItem',
        ),
    ]
